collaborator: Media #name of collaborator 
sources: 
  - name: media_customers
    csv_location: ./media_customers.csv
    description: table having data for media customer
    columns:
      - name: email 
        type: string
        masking_type: sha256
        selectable: true # can you run select query on this col
        aggregates_allowed: # no other aggregates are to be allowed. 
          - private_count
          - private_count_distinct  
        join_key: true # can this column be used as a join_key
      - name: phone_number # if aggregates_allowed not mentioned assume aggregates not allowed. 
        type: string 
        masking_type: sha256
        selectable: false
        aggregates_allowed: none
        join_key: true 
      - name: zip 
        type: string 
        selectable: true
        aggregates_allowed: 
          - count 
        masking_type: none
        join_key: false 
      - name: age_band
        type: number 
        masking_type: none
        aggregates_allowed: 
          - private_avg
          - std_dev
        selectable: true
        join_key: false
    consumers_allowed: # who is allowed to use this source in transformation
      - research
    destinations_allowed: 
      - ref: /Research/transformation/private_total_customers 
          - noise_parameters: 
          - epsilon: ln3 
          - delta: 1e-5
          - kappa: 1
          - threshold: between 0 and 3  